In [3]:
import pandas as pd 

df = pd.read_csv('airports.csv')

print(df)

                X          Y  OBJECTID                             GLOBAL_ID  \
0     -176.642498  51.883582         1  656D38F0-F1FE-49A8-AB4F-677281616EF8
1     -154.182576  56.938692         2  F39AFCD2-D07F-4F41-96CF-08B79A271EAB
2     -161.493351  60.913810         3  C0EE48D3-E3AD-404E-945D-F404E345020D
3     -161.435099  60.907865         4  26D96486-FA29-4866-93EB-2EEEB7FA7144
4     -161.230605  60.902897         5  C7DF2896-135E-487B-9172-2FF613E7EAF1
...           ...        ...       ...                                   ...
20172  -77.601669  36.044729     20173  F02F77CD-571F-48E9-9A3B-8451AB74773A
20173  -95.932488  29.632122     20174  E0512CBA-91B2-4270-91D4-6A8462CD2D79
20174 -123.452315  48.081139     20175  57337850-DC81-434E-BCB0-3CB9E9D10B74
20175 -123.004875  44.673061     20176  69458457-D4B3-4939-8DB6-30B569913F3E
20176 -122.409519  45.335042     20177  9F31FA57-2D61-42AB-ADC2-8832AD6F4840

      IDENT           NAME        LATITUDE        LONGITUDE  ELEVATION  \
0       ADK           Adak  51-53-00.8980N  176-38-32.9360W       19.5
1       AKK         Akhiok  56-56-19.2870N  154-10-57.2000W       44.4
2       Z13       Akiachak  60-54-49.7150N  161-29-35.9850W       22.8
3       KKI       Akiachak  60-54-28.3130N  161-26-06.2780W       18.0
4       AKI          Akiak  60-54-10.4300N  161-13-50.1000W       39.8
...     ...            ...             ...              ...        ...
20172  NR89   Steve's Farm  36-02-41.0000N  077-36-06.0000W      104.0
20173  03TT    Brazos Polo  29-37-55.6200N  095-55-56.9300W      117.0
20174  85WA  Delta Golf Lz  48-04-52.0800N  123-27-08.2800W      877.0
20175  OR82    Pair-A-Dice  44-40-23.0000N  123-00-17.5000W      290.0
20176  OR76      Cider Run  45-20-06.1327N  122-24-34.2181W      525.0

      ICAO_ID  ... FAR91 FAR93 MIL_CODE       AIRANAL US_HIGH  US_LOW  \
0        PADK  ...   0.0   0.0    CIVIL  NO OBJECTION       0       0
1        PAKH  ...   0.0   0.0    CIVIL  NO OBJECTION       0       0
2        PAZK  ...   0.0   0.0    CIVIL  NO OBJECTION       0       0
3         NaN  ...   0.0   0.0    CIVIL  NO OBJECTION       0       0
4        PFAK  ...   0.0   0.0    CIVIL  NO OBJECTION       0       0
...       ...  ...   ...   ...      ...           ...     ...     ...
20172     NaN  ...   0.0   0.0    CIVIL  NO OBJECTION       0       0
20173     NaN  ...   0.0   0.0    CIVIL  NO OBJECTION       0       0
20174     NaN  ...   0.0   0.0    CIVIL   CONDITIONAL       0       0
20175     NaN  ...   0.0   0.0    CIVIL   CONDITIONAL       0       0
20176     NaN  ...   0.0   0.0    CIVIL   CONDITIONAL       0       0

       AK_HIGH  AK_LOW  US_AREA  PACIFIC
0            1       1        0        0
1            0       1        0        0
2            0       1        0        0
3            0       0        0        0
4            0       1        0        0
...        ...     ...      ...      ...
20172        0       0        0        0
20173        0       0        0        0
20174        0       0        0        0
20175        0       0        0        0
20176        0       0        0        0

[20177 rows x 28 columns]

In [7]:
for col in df.columns: 
    print(col)

X
Y
OBJECTID
GLOBAL_ID
IDENT
NAME
LATITUDE
LONGITUDE
ELEVATION
ICAO_ID
TYPE_CODE
SERVCITY
STATE
COUNTRY
OPERSTATUS
PRIVATEUSE
IAPEXISTS
DODHIFLIP
FAR91
FAR93
MIL_CODE
AIRANAL
US_HIGH
US_LOW
AK_HIGH
AK_LOW
US_AREA
PACIFIC

In [47]:
df['PRIVATEUSE'] = df['PRIVATEUSE'].replace(['PPublic', 1], ['Public', 'Private'])

print(df[['PRIVATEUSE']])

      PRIVATEUSE
0         Public
1         Public
2         Public
3         Public
4         Public
...          ...
20172    Private
20173    Private
20174    Private
20175    Private
20176    Private

[20177 rows x 1 columns]

In [48]:
df['Obligations'] = 'Value'
df

,X,Y,OBJECTID,GLOBAL_ID,IDENT,NAME,LATITUDE,LONGITUDE,ELEVATION,ICAO_ID,...,MIL_CODE,AIRANAL,US_HIGH,US_LOW,AK_HIGH,AK_LOW,US_AREA,PACIFIC,Obligations,New_State
0,-176.642498,51.883582,1,656D38F0-F1FE-49A8-AB4F-677281616EF8,ADK,Adak,51-53-00.8980N,176-38-32.9360W,19.5,PADK,...,CIVIL,NO OBJECTION,0,0,1,1,0,0,Value,AK
1,-154.182576,56.938692,2,F39AFCD2-D07F-4F41-96CF-08B79A271EAB,AKK,Akhiok,56-56-19.2870N,154-10-57.2000W,44.4,PAKH,...,CIVIL,NO OBJECTION,0,0,0,1,0,0,Value,AK
2,-161.493351,60.913810,3,C0EE48D3-E3AD-404E-945D-F404E345020D,Z13,Akiachak,60-54-49.7150N,161-29-35.9850W,22.8,PAZK,...,CIVIL,NO OBJECTION,0,0,0,1,0,0,Value,AK
3,-161.435099,60.907865,4,26D96486-FA29-4866-93EB-2EEEB7FA7144,KKI,Akiachak,60-54-28.3130N,161-26-06.2780W,18.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,Value,AK
4,-161.230605,60.902897,5,C7DF2896-135E-487B-9172-2FF613E7EAF1,AKI,Akiak,60-54-10.4300N,161-13-50.1000W,39.8,PFAK,...,CIVIL,NO OBJECTION,0,0,0,1,0,0,Value,AK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20172,-77.601669,36.044729,20173,F02F77CD-571F-48E9-9A3B-8451AB74773A,NR89,Steve's Farm,36-02-41.0000N,077-36-06.0000W,104.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,Value,NC
20173,-95.932488,29.632122,20174,E0512CBA-91B2-4270-91D4-6A8462CD2D79,03TT,Brazos Polo,29-37-55.6200N,095-55-56.9300W,117.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,Value,TX
20174,-123.452315,48.081139,20175,57337850-DC81-434E-BCB0-3CB9E9D10B74,85WA,Delta Golf Lz,48-04-52.0800N,123-27-08.2800W,877.0,NaN,...,CIVIL,CONDITIONAL,0,0,0,0,0,0,Value,WA
20175,-123.004875,44.673061,20176,69458457-D4B3-4939-8DB6-30B569913F3E,OR82,Pair-A-Dice,44-40-23.0000N,123-00-17.5000W,290.0,NaN,...,CIVIL,CONDITIONAL,0,0,0,0,0,0,Value,OR
20176,-122.409519,45.335042,20177,9F31FA57-2D61-42AB-ADC2-8832AD6F4840,OR76,Cider Run,45-20-06.1327N,122-24-34.2181W,525.0,NaN,...,CIVIL,CONDITIONAL,0,0,0,0,0,0,Value,OR

In [49]:
df.loc[(df.STATE == 'AK'),'Obligations']='P'
df.loc[(df.STATE == 'CO'),'Obligations']='X'
df.loc[(df.STATE == 'CA'),'Obligations']='N'
df.loc[(df.STATE == 'WY'),'Obligations']='R'



print(df[['Obligations']])

      Obligations
0               P
1               P
2               P
3               P
4               P
...           ...
20172       Value
20173       Value
20174       Value
20175       Value
20176       Value

[20177 rows x 1 columns]

In [50]:
df.loc[df['STATE'] == "WY"]

,X,Y,OBJECTID,GLOBAL_ID,IDENT,NAME,LATITUDE,LONGITUDE,ELEVATION,ICAO_ID,...,MIL_CODE,AIRANAL,US_HIGH,US_LOW,AK_HIGH,AK_LOW,US_AREA,PACIFIC,Obligations,New_State
17814,-110.942183,42.708777,17815,439CB855-1C00-4869-BA68-11BA39D31078,AFO,Afton Muni,42-42-31.5740N,110-56-31.8160W,6220.9,KAFO,...,CIVIL,CONDITIONAL,1,1,0,0,0,0,R,WY
17815,-110.897992,42.861043,17816,CB66AB36-3434-4D15-ADAA-87FA92EC6013,WY60,Heiner,42-51-39.7330N,110-53-52.7290W,6440.0,NaN,...,CIVIL,CONDITIONAL,0,0,0,0,0,0,R,WY
17816,-111.038512,43.181812,17817,7BFA0C81-8A65-4601-938A-A89044CF1CD0,46U,Alpine,43-10-54.5000N,111-02-18.6000W,5637.0,NaN,...,CIVIL,NO OBJECTION,1,1,0,0,0,0,R,WY
17817,-108.163345,44.411118,17818,8A414805-914F-41BE-A3CB-D80FB3823E51,0WY1,Dorsey Creek Ranch,44-24-40.0000N,108-09-48.0000W,4017.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,R,WY
17818,-110.108873,42.582229,17819,8CC3A952-F5E6-411C-8A8A-0A496CD87CEC,BPI,Miley Meml Fld,42-34-56.0000N,110-06-31.9000W,6993.6,KBPI,...,CIVIL,NO OBJECTION,1,1,0,0,0,0,R,WY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18727,-105.743066,43.446118,18728,4B235E05-00ED-4B93-A76D-092EDD1980B0,84WY,Moore Ranch,43-26-46.0000N,105-44-35.0000W,5027.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,R,WY
18747,-105.511260,41.284729,18748,6928A147-2B32-4E82-B7FC-2081D95FBAD6,WY61,Rock & A Hard Place Ranch,41-17-05.0000N,105-30-40.5000W,7566.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,R,WY
18836,-106.224455,42.840368,18837,A9B182AC-C3EA-401E-89D2-64245ABE8022,00WY,Mountain View Rgnl Hospital,42-50-25.3000N,106-13-28.0000W,5209.3,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,R,WY
19948,-110.395984,42.544034,19949,4C2DDF7F-CBFD-47B3-9B7D-ED99674546C2,WY19,Fish Creek Ranch,42-32-38.5000N,110-23-45.5000W,7635.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,R,WY
19972,-104.825663,41.072784,19973,5B992499-3155-4F9B-BDE7-544439AE7A2B,WY46,Radio Ranch,41-04-22.0000N,104-49-32.3500W,6115.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,R,WY

In [51]:
df['New_State'] =  df['STATE'] 
df

,X,Y,OBJECTID,GLOBAL_ID,IDENT,NAME,LATITUDE,LONGITUDE,ELEVATION,ICAO_ID,...,MIL_CODE,AIRANAL,US_HIGH,US_LOW,AK_HIGH,AK_LOW,US_AREA,PACIFIC,Obligations,New_State
0,-176.642498,51.883582,1,656D38F0-F1FE-49A8-AB4F-677281616EF8,ADK,Adak,51-53-00.8980N,176-38-32.9360W,19.5,PADK,...,CIVIL,NO OBJECTION,0,0,1,1,0,0,P,AK
1,-154.182576,56.938692,2,F39AFCD2-D07F-4F41-96CF-08B79A271EAB,AKK,Akhiok,56-56-19.2870N,154-10-57.2000W,44.4,PAKH,...,CIVIL,NO OBJECTION,0,0,0,1,0,0,P,AK
2,-161.493351,60.913810,3,C0EE48D3-E3AD-404E-945D-F404E345020D,Z13,Akiachak,60-54-49.7150N,161-29-35.9850W,22.8,PAZK,...,CIVIL,NO OBJECTION,0,0,0,1,0,0,P,AK
3,-161.435099,60.907865,4,26D96486-FA29-4866-93EB-2EEEB7FA7144,KKI,Akiachak,60-54-28.3130N,161-26-06.2780W,18.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,P,AK
4,-161.230605,60.902897,5,C7DF2896-135E-487B-9172-2FF613E7EAF1,AKI,Akiak,60-54-10.4300N,161-13-50.1000W,39.8,PFAK,...,CIVIL,NO OBJECTION,0,0,0,1,0,0,P,AK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20172,-77.601669,36.044729,20173,F02F77CD-571F-48E9-9A3B-8451AB74773A,NR89,Steve's Farm,36-02-41.0000N,077-36-06.0000W,104.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,Value,NC
20173,-95.932488,29.632122,20174,E0512CBA-91B2-4270-91D4-6A8462CD2D79,03TT,Brazos Polo,29-37-55.6200N,095-55-56.9300W,117.0,NaN,...,CIVIL,NO OBJECTION,0,0,0,0,0,0,Value,TX
20174,-123.452315,48.081139,20175,57337850-DC81-434E-BCB0-3CB9E9D10B74,85WA,Delta Golf Lz,48-04-52.0800N,123-27-08.2800W,877.0,NaN,...,CIVIL,CONDITIONAL,0,0,0,0,0,0,Value,WA
20175,-123.004875,44.673061,20176,69458457-D4B3-4939-8DB6-30B569913F3E,OR82,Pair-A-Dice,44-40-23.0000N,123-00-17.5000W,290.0,NaN,...,CIVIL,CONDITIONAL,0,0,0,0,0,0,Value,OR
20176,-122.409519,45.335042,20177,9F31FA57-2D61-42AB-ADC2-8832AD6F4840,OR76,Cider Run,45-20-06.1327N,122-24-34.2181W,525.0,NaN,...,CIVIL,CONDITIONAL,0,0,0,0,0,0,Value,OR

In [52]:
print(df.iloc[17814:19972])

                X          Y  OBJECTID                             GLOBAL_ID  \
17814 -110.942183  42.708777     17815  439CB855-1C00-4869-BA68-11BA39D31078
17815 -110.897992  42.861043     17816  CB66AB36-3434-4D15-ADAA-87FA92EC6013
17816 -111.038512  43.181812     17817  7BFA0C81-8A65-4601-938A-A89044CF1CD0
17817 -108.163345  44.411118     17818  8A414805-914F-41BE-A3CB-D80FB3823E51
17818 -110.108873  42.582229     17819  8CC3A952-F5E6-411C-8A8A-0A496CD87CEC
...           ...        ...       ...                                   ...
19967  -84.476394  41.997950     19968  24A1835C-4DC4-4A2C-AE91-BE19CB28D892
19968  -96.716045  34.372576     19969  72BD7342-50F6-4311-9B43-6BD13979B008
19969  -82.640118  39.033021     19970  318BF864-1B04-45E3-BC52-B138F8481659
19970 -111.889706  40.486562     19971  8EA3158E-2C3B-494D-8044-F10D3473DCC5
19971 -113.258759  40.725081     19972  6E4C873E-A6EB-4851-B03D-1C53E53A9FAF

      IDENT                             NAME        LATITUDE        LONGITUDE  \
17814   AFO                       Afton Muni  42-42-31.5740N  110-56-31.8160W
17815  WY60                           Heiner  42-51-39.7330N  110-53-52.7290W
17816   46U                           Alpine  43-10-54.5000N  111-02-18.6000W
17817  0WY1               Dorsey Creek Ranch  44-24-40.0000N  108-09-48.0000W
17818   BPI                   Miley Meml Fld  42-34-56.0000N  110-06-31.9000W
...     ...                              ...             ...              ...
19967  79MI                        Davis Fld  41-59-52.5900N  084-28-35.0000W
19968  01OL          Spring Creek Ranch East  34-22-21.2512N  096-42-57.7339W
19969  OH00  Holzer Medical Center - Jackson  39-01-58.8500N  082-38-24.4100W
19970  42UT                   Pluralsight Hq  40-29-11.6000N  111-53-22.9000W
19971  UT57    Knolls Scene Landing Location  40-43-30.2700N  113-15-31.4900W

       ELEVATION ICAO_ID  ... MIL_CODE       AIRANAL US_HIGH US_LOW AK_HIGH  \
17814     6220.9    KAFO  ...    CIVIL   CONDITIONAL       1      1       0
17815     6440.0     NaN  ...    CIVIL   CONDITIONAL       0      0       0
17816     5637.0     NaN  ...    CIVIL  NO OBJECTION       1      1       0
17817     4017.0     NaN  ...    CIVIL  NO OBJECTION       0      0       0
17818     6993.6    KBPI  ...    CIVIL  NO OBJECTION       1      1       0
...          ...     ...  ...      ...           ...     ...    ...     ...
19967     1185.0     NaN  ...    CIVIL  NO OBJECTION       0      0       0
19968     1060.0     NaN  ...    CIVIL  NO OBJECTION       0      0       0
19969      740.0     NaN  ...    CIVIL  NO OBJECTION       0      0       0
19970     4738.0     NaN  ...    CIVIL  NO OBJECTION       0      0       0
19971     4253.0     NaN  ...    CIVIL  NO OBJECTION       0      0       0

      AK_LOW  US_AREA  PACIFIC  Obligations  New_State
17814      0        0        0            R         WY
17815      0        0        0            R         WY
17816      0        0        0            R         WY
17817      0        0        0            R         WY
17818      0        0        0            R         WY
...      ...      ...      ...          ...        ...
19967      0        0        0        Value         MI
19968      0        0        0        Value         OK
19969      0        0        0        Value         OH
19970      0        0        0        Value         UT
19971      0        0        0        Value         UT

[2158 rows x 30 columns]

In [60]:


df['New_ID'] = df.index + 1

df

,index,X,Y,OBJECTID,GLOBAL_ID,IDENT,NAME,LATITUDE,LONGITUDE,ELEVATION,...,AIRANAL,US_HIGH,US_LOW,AK_HIGH,AK_LOW,US_AREA,PACIFIC,Obligations,New_State,New_ID
0,0,-176.642498,51.883582,1,656D38F0-F1FE-49A8-AB4F-677281616EF8,ADK,Adak,51-53-00.8980N,176-38-32.9360W,19.5,...,NO OBJECTION,0,0,1,1,0,0,P,AK,1
1,1,-154.182576,56.938692,2,F39AFCD2-D07F-4F41-96CF-08B79A271EAB,AKK,Akhiok,56-56-19.2870N,154-10-57.2000W,44.4,...,NO OBJECTION,0,0,0,1,0,0,P,AK,2
2,2,-161.493351,60.913810,3,C0EE48D3-E3AD-404E-945D-F404E345020D,Z13,Akiachak,60-54-49.7150N,161-29-35.9850W,22.8,...,NO OBJECTION,0,0,0,1,0,0,P,AK,3
3,3,-161.435099,60.907865,4,26D96486-FA29-4866-93EB-2EEEB7FA7144,KKI,Akiachak,60-54-28.3130N,161-26-06.2780W,18.0,...,NO OBJECTION,0,0,0,0,0,0,P,AK,4
4,4,-161.230605,60.902897,5,C7DF2896-135E-487B-9172-2FF613E7EAF1,AKI,Akiak,60-54-10.4300N,161-13-50.1000W,39.8,...,NO OBJECTION,0,0,0,1,0,0,P,AK,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20172,20172,-77.601669,36.044729,20173,F02F77CD-571F-48E9-9A3B-8451AB74773A,NR89,Steve's Farm,36-02-41.0000N,077-36-06.0000W,104.0,...,NO OBJECTION,0,0,0,0,0,0,Value,NC,20173
20173,20173,-95.932488,29.632122,20174,E0512CBA-91B2-4270-91D4-6A8462CD2D79,03TT,Brazos Polo,29-37-55.6200N,095-55-56.9300W,117.0,...,NO OBJECTION,0,0,0,0,0,0,Value,TX,20174
20174,20174,-123.452315,48.081139,20175,57337850-DC81-434E-BCB0-3CB9E9D10B74,85WA,Delta Golf Lz,48-04-52.0800N,123-27-08.2800W,877.0,...,CONDITIONAL,0,0,0,0,0,0,Value,WA,20175
20175,20175,-123.004875,44.673061,20176,69458457-D4B3-4939-8DB6-30B569913F3E,OR82,Pair-A-Dice,44-40-23.0000N,123-00-17.5000W,290.0,...,CONDITIONAL,0,0,0,0,0,0,Value,OR,20176
20176,20176,-122.409519,45.335042,20177,9F31FA57-2D61-42AB-ADC2-8832AD6F4840,OR76,Cider Run,45-20-06.1327N,122-24-34.2181W,525.0,...,CONDITIONAL,0,0,0,0,0,0,Value,OR,20177

In [65]:
df.loc[df['STATE'] == "WY"]

,index,X,Y,OBJECTID,GLOBAL_ID,IDENT,NAME,LATITUDE,LONGITUDE,ELEVATION,...,AIRANAL,US_HIGH,US_LOW,AK_HIGH,AK_LOW,US_AREA,PACIFIC,Obligations,New_State,New_ID
17814,17814,-110.942183,42.708777,17815,439CB855-1C00-4869-BA68-11BA39D31078,AFO,Afton Muni,42-42-31.5740N,110-56-31.8160W,6220.9,...,CONDITIONAL,1,1,0,0,0,0,R,WY,17815
17815,17815,-110.897992,42.861043,17816,CB66AB36-3434-4D15-ADAA-87FA92EC6013,WY60,Heiner,42-51-39.7330N,110-53-52.7290W,6440.0,...,CONDITIONAL,0,0,0,0,0,0,R,WY,17816
17816,17816,-111.038512,43.181812,17817,7BFA0C81-8A65-4601-938A-A89044CF1CD0,46U,Alpine,43-10-54.5000N,111-02-18.6000W,5637.0,...,NO OBJECTION,1,1,0,0,0,0,R,WY,17817
17817,17817,-108.163345,44.411118,17818,8A414805-914F-41BE-A3CB-D80FB3823E51,0WY1,Dorsey Creek Ranch,44-24-40.0000N,108-09-48.0000W,4017.0,...,NO OBJECTION,0,0,0,0,0,0,R,WY,17818
17818,17818,-110.108873,42.582229,17819,8CC3A952-F5E6-411C-8A8A-0A496CD87CEC,BPI,Miley Meml Fld,42-34-56.0000N,110-06-31.9000W,6993.6,...,NO OBJECTION,1,1,0,0,0,0,R,WY,17819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18727,18727,-105.743066,43.446118,18728,4B235E05-00ED-4B93-A76D-092EDD1980B0,84WY,Moore Ranch,43-26-46.0000N,105-44-35.0000W,5027.0,...,NO OBJECTION,0,0,0,0,0,0,R,WY,18728
18747,18747,-105.511260,41.284729,18748,6928A147-2B32-4E82-B7FC-2081D95FBAD6,WY61,Rock & A Hard Place Ranch,41-17-05.0000N,105-30-40.5000W,7566.0,...,NO OBJECTION,0,0,0,0,0,0,R,WY,18748
18836,18836,-106.224455,42.840368,18837,A9B182AC-C3EA-401E-89D2-64245ABE8022,00WY,Mountain View Rgnl Hospital,42-50-25.3000N,106-13-28.0000W,5209.3,...,NO OBJECTION,0,0,0,0,0,0,R,WY,18837
19948,19948,-110.395984,42.544034,19949,4C2DDF7F-CBFD-47B3-9B7D-ED99674546C2,WY19,Fish Creek Ranch,42-32-38.5000N,110-23-45.5000W,7635.0,...,NO OBJECTION,0,0,0,0,0,0,R,WY,19949
19972,19972,-104.825663,41.072784,19973,5B992499-3155-4F9B-BDE7-544439AE7A2B,WY46,Radio Ranch,41-04-22.0000N,104-49-32.3500W,6115.0,...,NO OBJECTION,0,0,0,0,0,0,R,WY,19973

In [66]:
print(df.iloc[17814:19972])

       index           X          Y  OBJECTID  \
17814  17814 -110.942183  42.708777     17815
17815  17815 -110.897992  42.861043     17816
17816  17816 -111.038512  43.181812     17817
17817  17817 -108.163345  44.411118     17818
17818  17818 -110.108873  42.582229     17819
...      ...         ...        ...       ...
19967  19967  -84.476394  41.997950     19968
19968  19968  -96.716045  34.372576     19969
19969  19969  -82.640118  39.033021     19970
19970  19970 -111.889706  40.486562     19971
19971  19971 -113.258759  40.725081     19972

                                  GLOBAL_ID IDENT  \
17814  439CB855-1C00-4869-BA68-11BA39D31078   AFO
17815  CB66AB36-3434-4D15-ADAA-87FA92EC6013  WY60
17816  7BFA0C81-8A65-4601-938A-A89044CF1CD0   46U
17817  8A414805-914F-41BE-A3CB-D80FB3823E51  0WY1
17818  8CC3A952-F5E6-411C-8A8A-0A496CD87CEC   BPI
...                                     ...   ...
19967  24A1835C-4DC4-4A2C-AE91-BE19CB28D892  79MI
19968  72BD7342-50F6-4311-9B43-6BD13979B008  01OL
19969  318BF864-1B04-45E3-BC52-B138F8481659  OH00
19970  8EA3158E-2C3B-494D-8044-F10D3473DCC5  42UT
19971  6E4C873E-A6EB-4851-B03D-1C53E53A9FAF  UT57

                                  NAME        LATITUDE        LONGITUDE  \
17814                       Afton Muni  42-42-31.5740N  110-56-31.8160W
17815                           Heiner  42-51-39.7330N  110-53-52.7290W
17816                           Alpine  43-10-54.5000N  111-02-18.6000W
17817               Dorsey Creek Ranch  44-24-40.0000N  108-09-48.0000W
17818                   Miley Meml Fld  42-34-56.0000N  110-06-31.9000W
...                                ...             ...              ...
19967                        Davis Fld  41-59-52.5900N  084-28-35.0000W
19968          Spring Creek Ranch East  34-22-21.2512N  096-42-57.7339W
19969  Holzer Medical Center - Jackson  39-01-58.8500N  082-38-24.4100W
19970                   Pluralsight Hq  40-29-11.6000N  111-53-22.9000W
19971    Knolls Scene Landing Location  40-43-30.2700N  113-15-31.4900W

       ELEVATION  ...       AIRANAL US_HIGH US_LOW AK_HIGH AK_LOW US_AREA  \
17814     6220.9  ...   CONDITIONAL       1      1       0      0       0
17815     6440.0  ...   CONDITIONAL       0      0       0      0       0
17816     5637.0  ...  NO OBJECTION       1      1       0      0       0
17817     4017.0  ...  NO OBJECTION       0      0       0      0       0
17818     6993.6  ...  NO OBJECTION       1      1       0      0       0
...          ...  ...           ...     ...    ...     ...    ...     ...
19967     1185.0  ...  NO OBJECTION       0      0       0      0       0
19968     1060.0  ...  NO OBJECTION       0      0       0      0       0
19969      740.0  ...  NO OBJECTION       0      0       0      0       0
19970     4738.0  ...  NO OBJECTION       0      0       0      0       0
19971     4253.0  ...  NO OBJECTION       0      0       0      0       0

      PACIFIC  Obligations  New_State  New_ID
17814       0            R         WY   17815
17815       0            R         WY   17816
17816       0            R         WY   17817
17817       0            R         WY   17818
17818       0            R         WY   17819
...       ...          ...        ...     ...
19967       0        Value         MI   19968
19968       0        Value         OK   19969
19969       0        Value         OH   19970
19970       0        Value         UT   19971
19971       0        Value         UT   19972

[2158 rows x 32 columns]